'use client';
import {useState,type FormEvent} from 'react';
import { SketchButton } from './sketch-button';
import {normalizePreferenceValue} from '@/lib/preferences';
import type { Preference, PreferenceBoundary, PreferenceKind } from '@/lib/preferences';
const kinds:Record<PreferenceKind,string>={hard_constraint:'Harde grens',soft_constraint:'Zachte grens',strong_preference:'Sterke voorkeur',weak_preference:'Lichte voorkeur',interest:'Nieuwsgierigheid',personal_wish:'Eigen wens',open_question:'Nog open'};
const labels:Record<string,string>={transport:'Vervoer',flight:'Vliegen',months:'Reisduur',departureMonth:'Vertrekmaand',monthlyBudget:'Maandbudget samen',temperature:'Warmte',beach:'Zee',community:'Community',spirituality:'Spiritualiteit',learning:'Leren',volunteering:'Vrijwilligen',playfulness:'Spelen',slowTravel:'Langzaam reizen',vegetarian:'Plantaardig eten',sailing:'Een paar dagen zeilen',personalDream:'Eigen dromen'};
const valueLabels:Record<string,string>={car:'Onze eigen auto',avoid:'Liever geen vliegtuig',warm_and_dry:'Warm en droog'};
export function PreferenceEditor({preferences,busy,onSave}:{preferences:Preference[];busy:boolean;onSave:(payload:Record<string,unknown>)=>Promise<unknown>}){
  const [error,setError]=useState('');
  async function submit(event:FormEvent<HTMLFormElement>,preference:Preference){
    event.preventDefault();setError('');const form=new FormData(event.currentTarget);
    const raw=String(form.get('value')??'').trim();const value=preference.value===null?(raw?raw:null):typeof preference.value==='boolean'?raw==='true':typeof preference.value==='number'?raw:raw===valueLabels[String(preference.value)]?String(preference.value):raw;
    const boundary:PreferenceBoundary|null=preference.boundary?{unit:preference.boundary.unit,exceptions:preference.boundary.exceptions}:null;
    if(boundary)for(const key of ['preferred','acceptable','hard'] as const){const low=String(form.get(`${key}Min`)??''),high=String(form.get(`${key}Max`)??'');if((low==='')!==(high==='')){setError('Vul bij een grens zowel vanaf als tot in.');return;}if(low!==''&&high!==''){if(!Number.isFinite(Number(low))||!Number.isFinite(Number(high))||Number(low)>Number(high)){setError('De grens vanaf moet kleiner dan of gelijk aan tot zijn.');return;}boundary[key]=[Number(low),Number(high)];}}
    let normalized;try{normalized=normalizePreferenceValue(preference.attribute,value);}catch(error){setError(error instanceof Error?error.message:'Controleer je afspraak.');return;}
    await onSave({action:'preference',preferenceId:preference.key,kind:form.get('kind'),notes:form.get('notes'),value:normalized,confidence:Number(form.get('confidence')),boundary});
  }
  return <div className="preference-list">{error&&<p role="alert">{error}</p>}{preferences.map(p=><details className="paper" key={p.key}><summary><b>{labels[p.attribute]??p.attribute}</b><span>{p.subject==='couple'?'Samen':p.subject==='roebie'?'Roebie':'Oelie'} · {kinds[p.kind]}</span></summary><form key={JSON.stringify(p)} onSubmit={e=>void submit(e,p)}><p>{p.notes}</p><label>Wat betekent dit voor ons?<select name="kind" defaultValue={p.kind}>{Object.entries(kinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Wens of afspraak{typeof p.value==='boolean'?<select name="value" defaultValue={String(p.value)}><option value="true">Ja, dit past bij ons</option><option value="false">Nee, dit past niet bij ons</option></select>:<input name="value" defaultValue={p.value===null?'':(valueLabels[String(p.value)]??String(p.value))} placeholder="Mag nog open blijven" maxLength={1000}/>}</label>{p.boundary&&(['preferred','acceptable','hard'] as const).map(key=><div className="boundary-inputs" key={key}><span>{key==='preferred'?'Liefst':key==='acceptable'?'Ook oké':'Absolute grens'} ({p.boundary!.unit})</span><label>Vanaf<input type="number" step="any" name={`${key}Min`} defaultValue={p.boundary?.[key]?.[0]}/></label><label>Tot<input type="number" step="any" name={`${key}Max`} defaultValue={p.boundary?.[key]?.[1]}/></label></div>)}<label>Hoe zeker zijn we?<select name="confidence" defaultValue={p.confidence}><option value={p.confidence}>Huidige zekerheid: {Math.round(p.confidence*100)}%</option><option value="0">Nog helemaal open</option><option value="0.5">Ongeveer wel</option><option value="1">Heel zeker</option></select></label><label>Toelichting en uitzonderingen<textarea name="notes" defaultValue={p.notes} maxLength={1000}/></label><SketchButton type="submit" disabled={busy}>Bewaar dit uitgangspunt</SketchButton></form></details>)}</div>;
}
