'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, Bookmark, Check, Compass, Home, Sofa, Sparkles, Settings, History, X, Bell, Download, Link as LinkIcon, LogOut, Sun, Map, Heart } from 'lucide-react';
import { Avatar, Landscape } from './illustrations';
import { SketchButton } from './sketch-button';
import { Travelers } from './travelers';
import { TravelPhoto } from './travel-photo';
import { PreferenceEditor } from './preference-editor';
import { PreviewToolbar } from './preview-toolbar';
import { AVATARS } from '@/lib/characters';
import { initialPreview, previewDashboard, previewAnswer, previewWeek, previewQuestions, previewNextSet } from '@/lib/demo';
import { questions as bank } from '@/lib/questions';
import type { dashboard } from '@/lib/service';
import type { Question } from '@/lib/domain';
const exampleQuestion=bank.find(q=>q.role)!;
type Data=Awaited<ReturnType<typeof dashboard>>;
type CardQuestion=Question & {own:number|null;partner:number|null;same:boolean|null};
type InstallEvent=Event & {prompt:()=>Promise<void>};
const nav=[{id:'today',label:'Vandaag',icon:Home},{id:'saved',label:'Op de bank',icon:Sofa},{id:'insights',label:'Reis-DNA',icon:Compass},{id:'report',label:'Reisrapport',icon:Map}];
const types:Record<string,string>={'trade-off':'De afweging',extreme:'Het grote dilemma',scenario:'Twee mini-reizen','one-change':'Eén verschil',wildcard:'De wildcard',boundary:'Waar ligt jouw grens?',refinement:'Even scherper',conditional:'Als dit, dan…',conflict:'Ruimte voor elkaar','personal-dream':'Jouw eigen droom',bundle:'Een pakketje mogelijkheden'};
export function TravelApp({demo=false}:{demo?:boolean}) {
  const [preview,setPreview]=useState(initialPreview);
  const [liveData,setData]=useState<Data|null>(null); const data=demo?previewDashboard(preview):liveData; const [loaded,setLoaded]=useState(demo); const [screen,setScreen]=useState(demo?'question':'today'); const [qid,setQid]=useState(demo?previewQuestions[0].id:'q061'); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [auth,setAuth]=useState<'register'|'login'|null>(null); const [avatar,setAvatar]=useState(0); const [inviteInput,setInviteInput]=useState(''); const [install,setInstall]=useState<InstallEvent|null>(null); const [selected,setSelected]=useState<number|null>(null);
  const refresh=useCallback(async()=>{if(demo)return;try {const res=await fetch('/api/app',{cache:'no-store'});if(!res.ok)throw Error('Verbinding met de app is even weg.');const value=await res.json();setData(value.user?value:null);setLoaded(true);if(value.user&&!new URLSearchParams(location.search).has('screen')){const pending=value.questions.find((q:CardQuestion)=>q.own===null&&!value.saved.some((s:CardQuestion)=>s.id===q.id));setScreen(pending?'question':'done');if(pending)setQid(pending.id);}return value as Data;}catch{setNotice('Geen verbinding. Je antwoorden blijven bewaard op de server.');setLoaded(true);}},[demo]);
  useEffect(()=>{if(!auth)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('[role="dialog"]');queueMicrotask(()=>dialog?.querySelector<HTMLElement>('input')?.focus());const trap=(event:KeyboardEvent)=>{if(event.key==='Escape'){setAuth(null);return;}if(event.key!=='Tab'||!dialog)return;const items=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input,a[href]'));const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}};window.addEventListener('keydown',trap);return()=>{window.removeEventListener('keydown',trap);previous?.focus();};},[auth]);
  useEffect(()=>{queueMicrotask(()=>void refresh());const timer=demo?undefined:setInterval(()=>void refresh(),20000);const sync=()=>{const p=new URLSearchParams(location.search);setScreen(p.get('screen')??(demo?'question':'today'));setQid(p.get('q')??(demo?previewQuestions[0].id:'q061'));setInviteInput(p.get('invite')??'');};queueMicrotask(sync);window.addEventListener('popstate',sync);const prompt=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};window.addEventListener('beforeinstallprompt',prompt);if(!demo&&'serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js');return()=>{clearInterval(timer);window.removeEventListener('popstate',sync);window.removeEventListener('beforeinstallprompt',prompt);};},[refresh,demo]);
  function go(next:string,q?:string) {if(next==='settings'&&data)setAvatar(data.user.avatar);setScreen(next);if(q)setQid(q);setSelected(null);history.pushState({},'',`${demo?'/test':'/'}?screen=${next}${q?`&q=${q}`:''}`);window.scrollTo({top:0,behavior:'smooth'});}
  async function action(payload:Record<string,unknown>) {
    if(demo){
      switch(payload.action){
        case 'preference':setPreview(state=>({...state,preferences:state.preferences.map(p=>p.key===payload.preferenceId?{...p,kind:payload.kind as typeof p.kind,value:payload.value,confidence:Number(payload.confidence),notes:String(payload.notes),boundary:payload.boundary as typeof p.boundary}:p)}));setNotice('Uitgangspunt geprobeerd. Alleen in deze testronde.');return true;
        case 'next-set':{const next=previewNextSet(preview);if(next===preview){setNotice('Er zijn geen nieuwe vragen meer in deze testronde.');return false;}setPreview(next);return previewDashboard(next);}
        case 'answer':setPreview(state=>previewAnswer(state,String(payload.questionId),Number(payload.choice)));return true;
        case 'save':setPreview(state=>({...state,saved:[...new Set([...state.saved,String(payload.questionId)])]}));return true;
        case 'feedback':setPreview(state=>({...state,feedback:String(payload.rating)}));setNotice('Alleen geprobeerd. Deze feedback wordt niet opgeslagen.');return true;
        default:setNotice('Dit is een proefscherm. Accounts, profielwijzigingen en notificaties worden hier niet opgeslagen.');return false;
      }
    }
    setBusy(true);setNotice('');try {const res=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await res.json();if(!res.ok)throw Error(result.error);return await refresh()??true;}catch(e){setNotice(e instanceof Error?e.message:'Er ging iets mis.');return false;}finally{setBusy(false);}}
  async function submitAuth(e:FormEvent<HTMLFormElement>) {e.preventDefault();const form=new FormData(e.currentTarget);if(await action({action:auth,...Object.fromEntries(form),avatar})){setAuth(null);if(auth==='login'){const requested=new URLSearchParams(location.search);if(requested.get('screen')==='question')go('question',requested.get('q')??'q001');else{history.replaceState({},'','/');void refresh();}}else go('pair');}}
  const today=data?.questions??[];const remaining=today.filter(q=>q.own===null&&!data?.saved.some(s=>s.id===q.id));
  const current=([...(data?.questions??[]),...(data?.saved??[]),...(data?.history??[]),...(data?.setArchive.flatMap(s=>s.questions)??[])].find(q=>q.id===qid)??{...(bank.find(q=>q.id===qid)??exampleQuestion),own:null,partner:null,same:null}) as CardQuestion;
  const partner=data?.members.find(m=>m.id!==data.user.id); const completed=today.filter(q=>q.own!==null).length;
  async function choose(choice:number,q:CardQuestion) { if(!data){setAuth('register');return;}setSelected(choice);if(await action({action:'answer',questionId:q.id,choice,mode:data.saved.some(saved=>saved.id===q.id)?'later':'daily'})){const sequence=data.setArchive.find(s=>s.questions.some(item=>item.id===q.id))?.questions??today;const next=sequence.find(item=>item.id!==q.id&&item.own===null&&!data.saved.some(saved=>saved.id===item.id));go(next?'question':today.some(item=>item.id===q.id)?'done':'sets',next?.id);}else setSelected(null); }
  async function enablePush() {if(demo){setNotice('In de testmodus vragen we geen toestemming en sturen we geen echte notificatie. Probeer Test berichtje.');return;}if(!data?.pushConfigured){setNotice('Notificaties worden beschikbaar zodra de VAPID-sleutels voor hosting zijn ingesteld.');return;}if(!('Notification'in window)||!('PushManager'in window)||!window.isSecureContext){setNotice('Push heeft HTTPS nodig. Op iPhone: installeer de app eerst via Safari.');return;}try{const permission=await Notification.requestPermission();if(permission!=='granted'){setNotice('Geen probleem. Je kunt de app altijd zelf openen.');return;}const sw=await navigator.serviceWorker.ready;const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY!;const raw=atob(key.replace(/-/g,'+').replace(/_/g,'/'));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const sub=await sw.pushManager.getSubscription()??await sw.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});if(await action({action:'subscribe',subscription:sub.toJSON()}))setNotice('Aan! We sturen alleen tussen 09:00 en 21:00 een berichtje.');}catch{setNotice('Push activeren lukte niet. Controleer je browserinstellingen.');}}
  const report=data?.report.content as ReturnType<typeof import('@/lib/domain').createReport>|undefined;
  async function startNextSet(){if(!data?.set)return;const result=await action({action:'next-set',setId:data.set.id});if(result&&typeof result==='object'){const next=result.questions.find(q=>q.own===null&&!result.saved.some(saved=>saved.id===q.id));go(next?'question':'done',next?.id);}}
  function setTotals(){return <div className="set-totals" aria-label="Totaal volledig beantwoorde sets">{data?.setTotals.map(person=><div key={person.userId}><Avatar id={person.avatar} size={38}/><span><b>{person.name}</b><small>{person.completed} {person.completed===1?'set':'sets'} beantwoord</small></span></div>)}</div>;}
  function questionCards(q:CardQuestion,interactive=true) {return <div className="battle">{q.options.map((option,i)=><article className={`option option-${i} ${selected===i?'chosen':''}`} key={i}><div className="option-top"><span className="letter">{i===0?'A':'B'}</span><span className="hand">{i===0?'dit trekt me':'of toch dit…'}</span></div><TravelPhoto option={option} questionId={q.id} index={i}/><div className="option-copy"><h3>{option.title}</h3><p>{option.subtitle}</p><ul>{option.details.map(d=><li key={d}><Check size={15}/>{d}</li>)}</ul></div>{interactive&&<button className="choice" aria-label={q.own===null?`Ik kies ${i===0?'A':'B'}: ${option.title}`:q.own===i?'Jouw keuze':'Keuze opgeslagen'} disabled={busy||q.own!==null} onClick={()=>void choose(i,q)}>{q.own===i?<><Check size={18}/> Jouw keuze</>:q.own!==null?'Keuze opgeslagen':<>Ik kies {i===0?'A':'B'} <ArrowRight size={18}/></>}</button>}</article>)}<span className="or hand">of</span></div>;}

  return <div className={`app ${demo?'is-demo':''} ${screen==='question'?'daily-flow':''}`}><aside className="sidebar"><Link href={demo?'/test':'/'} className="brand"><Compass size={29}/><span>samen<br/><b>op reis.</b></span></Link><p className="brand-note hand">kleine keuzes, groot avontuur</p><nav aria-label="Hoofdnavigatie">{nav.map(item=><button key={item.id} className={screen===item.id?'active':''} onClick={()=>go(item.id)}><item.icon size={20}/>{item.label}{item.id==='saved'&&!!data?.saved.length&&<span className="count">{data.saved.length}</span>}</button>)}</nav><div className="sidebar-bottom"><p className="hand">Nog niet weten waar.<br/>Wel weten met wie.</p><div className="pair-mini"><Travelers members={data?.members.length===2?data.members:undefined} size={38}/></div><button className="quiet" onClick={()=>go('settings')}><Settings size={17}/> Instellingen</button></div></aside>
    <main>{screen!=='question'&&<header className="topbar"><span className="date"><Sun size={17}/>{new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'long',timeZone:'Europe/Amsterdam'}).format(new Date())}<span className="desktop-only"> · een beetje voorpret</span></span><div className="header-actions">{!demo&&<Link href="/test" className="quiet">Testflow</Link>}{data?<button className="user-chip" onClick={()=>go('settings')}>{screen!=='today'&&<Avatar id={data.user.avatar} size={30}/>}{data.user.name}</button>:<button className="quiet" onClick={()=>setAuth('login')}>Inloggen <ArrowRight size={16}/></button>}</div></header>}
    {notice&&<div className="notice" role="status">{notice}<button aria-label="Melding sluiten" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    <div className="content">

    {demo&&screen==='notification'&&<section className="paper notification-preview"><span className="eyebrow">ZO BEGINT JULLIE DAGELIJKSE MOMENT</span><h1>Stel: dit komt binnen.</h1><p>Dit is een voorbeeldberichtje. Tik erop en je zit meteen bij de keuzes.</p><button className="notification-message" onClick={()=>go(remaining.length?'question':'done',remaining[0]?.id)}><Travelers members={data?.members} size={38}/><span><b>Samen op reis</b><small>Vier kleine keuzes. Een beetje dichter bij jullie reis.</small></span><ArrowRight size={20}/></button></section>}
    {screen==='done'&&<section className="paper daily-done"><span className="eyebrow">SET {data?.set?.ordinal??1} · {today.length} VRAGEN</span><h1>{completed===today.length&&today.length?'Een setje dichterbij.':'Even laten bezinken.'}</h1><p>{completed} van de {today.length} vragen beantwoord. Bewaarde vragen tellen mee zodra je ze ook beantwoordt.</p>{setTotals()}<SketchButton disabled={busy||!data?.set} onClick={()=>void startNextSet()}>Nog een set <ArrowRight size={18}/></SketchButton><button className="quiet" onClick={()=>go('today')}>Genoeg voor nu</button><button className="quiet" onClick={()=>go('sets')}>Bekijk alle sets</button><button className="quiet" onClick={()=>go('history')}>Bekijk jullie keuzes <History size={17}/></button>{!!data?.saved.length&&<button className="quiet" onClick={()=>go('saved')}>Bewaarde vragen beantwoorden <Sofa size={18}/></button>}</section>}


    {screen==='today'&&<><div className="welcome"><div><span className="eyebrow">JULLIE VOLGENDE REIS BEGINT HIER</span><h1>Waar dromen<br/>we vandaag van<span className="question-mark">?</span></h1><p>Geen lijstjes. Geen plannen. Alleen een paar kleine<br className="desktop-only"/> keuzes die jullie dichter bij jullie grote avontuur brengen.</p></div><div className="welcome-art"><Landscape/><span className="hand">ergens, samen.</span></div></div><section className="daily-strip"><div><span className="sun-disc"><Sun size={24}/></span><div><h2>{data?remaining.length?`${remaining.length} vragen in deze set`:'Jullie keuzes staan in het boekje':'Een kleine keuze. Een groot avontuur.'}</h2><p>{data?`Set ${data.set?.ordinal??1} · ${completed} van de ${today.length} beantwoord`:'Zo ziet jullie dagelijkse reisspelletje eruit. Probeer de eerste vraag.'}</p></div></div><SketchButton onClick={()=>data?go(remaining.length?'question':'done',remaining[0]?.id):setAuth('register')}>{data?'Verder met onze set':'Begin samen'} <ArrowRight size={18}/></SketchButton></section><section className="sample"><div className="section-label"><span className="eyebrow">{data?'UIT JULLIE BOEKJE':'EEN VOORPROEFJE'}</span><span className="stamp">2 minuten voorpret</span></div><h2>{data?(remaining[0]??today[0])?.title??'De wereld wacht wel even.':exampleQuestion.title}</h2><p className="section-intro">{data?'Welke kant trekt jou vandaag?':exampleQuestion.intro}</p>{questionCards((data?(remaining[0]??today[0]??{...exampleQuestion,own:null,partner:null,same:null}):{...exampleQuestion,own:null,partner:null,same:null}) as CardQuestion)}<button className="save-link" disabled={busy} onClick={()=>{if(!data){setAuth('register');return;}const q=remaining[0]??today[0];if(q)void action({action:'save',questionId:q.id}).then(ok=>{if(ok)setNotice('Bewaard voor een avond samen op de bank.');});}}><Bookmark size={17}/>Deze bewaren we voor op de bank</button></section>{setTotals()}{data&&<button className="quiet all-sets-link" onClick={()=>go('sets')}>Alle sets in ons boekje <History size={17}/></button>}<div className="bottom-cards"><button className="small-card" onClick={()=>go('saved')}><Sofa size={26}/><div><h3>Samen op de bank</h3><p>{data?.saved.length??0} bewaarde dilemma’s · voor later</p></div><ArrowRight size={20}/></button><button className="small-card report-teaser" onClick={()=>go('report')}><Sparkles size={25}/><div><h3>Een reis die op jullie lijkt</h3><p>Jullie reisverhaal, elke week een beetje scherper</p></div><ArrowRight size={20}/></button></div><Link href="/test" className="preview-entry"><Sparkles size={17}/> Probeer de testflow zonder account of opslag <ArrowRight size={17}/></Link><p className="footer-note hand">de mooiste reis begint met: “wat als…”</p></>}
    {screen==='sets'&&<><div className="page-heading"><span className="eyebrow">JULLIE VERZAMELING KLEINE KEUZES</span><h1>Alle sets in ons boekje.</h1><p>Ook een eerdere set kun je later afmaken. De teller telt alleen volledig beantwoorde sets.</p></div>{setTotals()}<div className="list">{data?.setArchive.map(set=><section className="paper archive-set" key={set.id}><h2>Set {set.ordinal} · {set.day}</h2><p>{set.questions.filter(q=>q.own!==null).length} van de {set.questions.length} door jou beantwoord</p>{set.questions.map(q=><button className="archive-question" key={q.id} onClick={()=>go(q.own!==null?'reveal':'question',q.id)}><span>{q.own!==null?<Check size={16}/>:<Compass size={16}/>}</span><span>{q.title}</span><ArrowRight size={16}/></button>)}</section>)}</div></>}
    {screen==='question'&&<><div className="daily-heading"><h1>{current.title}</h1><span className="daily-count" aria-label="Vraagnummer">{today.some(q=>q.id===current.id)?`${Math.max(0,today.findIndex(q=>q.id===current.id))+1} / ${today.length}`:'Bewaard'}</span></div>{questionCards(current)}<button className="save-link" disabled={busy} onClick={()=>data?void action({action:'save',questionId:current.id}).then(ok=>{if(ok){const sequence=data.setArchive.find(s=>s.questions.some(q=>q.id===current.id))?.questions??today;const next=sequence.find(q=>q.id!==current.id&&q.own===null&&!data.saved.some(saved=>saved.id===q.id));go(next?'question':today.some(q=>q.id===current.id)?'done':'sets',next?.id);}}):setAuth('register')}><Bookmark size={18}/>Bewaar voor later</button><p className="privacy-note">Jouw keuze blijft geheim tot jullie allebei hebben gekozen.</p></>}
    {screen==='reveal'&&<section className="reveal paper"><span className="eyebrow">EEN BLADZIJDE IN JULLIE REISVERHAAL</span><div className="reveal-avatars"><Travelers members={data?.members.length===2?data.members:undefined} size={82}/></div><h1>{current.same===true?'Dezelfde kant op.':current.same===false?'Twee kanten. Eén avontuur.':'Jouw keuze staat in het boekje.'}</h1><p>{current.same===true?'Jullie kozen hetzelfde. Dat is een klein stukje van jullie reis-DNA.':current.same===false?'Hier verschillen jullie. Leuk om later eens over door te praten.':'Nog even geheim. Zodra je partner ook kiest, verschijnt jullie moment hier vanzelf.'}</p><h3>{current.title}</h3><div className="reveal-result"><p>{data?.user.name}: <b>{current.own===null?'nog niet gekozen':current.options[current.own].title}</b></p><p>{partner?.name??'Je partner'}: <b>{current.partner===null?'nog een verrassing':current.options[current.partner].title}</b></p></div><SketchButton onClick={()=>{const next=remaining.find(q=>q.id!==current.id);go(next?'question':'done',next?.id);}}>{remaining.some(q=>q.id!==current.id)?'Verder met de set':'Set afgerond'} <ArrowRight size={17}/></SketchButton><button className="quiet" onClick={()=>go('today')}>Genoeg gedroomd voor nu</button></section>}
    {(screen==='saved'||screen==='history')&&<><div className="page-heading"><span className="eyebrow">JULLIE REISNOTITIEBOEK</span><h1>{screen==='saved'?'Samen op de bank.':'De keuzes tot nu toe.'}</h1><p>{screen==='saved'?'Thee erbij. Telefoons erbij. Een stapeltje “wat als”. Antwoord ieder op je eigen account.':'Een reis ontstaat niet in één dag. Hier vind je jullie kleine stappen.'}</p></div>{!data?<Empty text="Maak jullie boekje aan om keuzes te bewaren." onClick={()=>setAuth('register')}/>:!(screen==='saved'?data.saved:data.history).length?<Empty text={screen==='saved'?'De bank is nog leeg. Bewaar een dilemma voor later.':'De eerste bladzijde is nog leeg.'} onClick={()=>go('today')}/>:<div className="list">{(screen==='saved'?data.saved:data.history).map(q=><button className="list-item paper" key={q.id} onClick={()=>go(q.own!==null?'reveal':'question',q.id)}><span className="list-icon">{screen==='saved'?<Sofa/>:<Check/>}</span><div><span className="eyebrow">{types[q.type]}</span><h3>{q.title}</h3><p>{q.same===true?'Samen dezelfde keuze':q.same===false?'Hier kozen jullie anders':q.own!==null?'Jouw keuze staat vast · partner nog geheim':'Nog een mooi gesprek te gaan'}</p></div><ArrowRight size={20}/></button>)}</div>}</>}
    {screen==='insights'&&<><div className="page-heading"><span className="eyebrow">LANGZAAM LEREN WE JULLIE KENNEN</span><h1>Jullie reis-DNA.</h1><p>Geen wetenschap. Wel steeds beter weten waar jullie blij van worden.</p></div><Travelers members={data?.members.length===2?data.members:undefined} size={54}/><div className="insight-grid"><div className="paper metric"><Compass size={35}/><strong>{data?.insights.match===null||!data?'—':`${data.insights.match}%`}</strong><h3>Dezelfde kant op</h3><p>Speelse score op basis van {data?.insights.complete??0} gezamenlijk beantwoorde dilemma’s. Geen voorspelling van jullie relatie.</p></div><div className="paper"><span className="eyebrow">DIT KEERT TERUG</span><h2>Kleine overeenkomsten</h2>{data?.insights.agreements.length?<ul className="plain-list">{[...new Set(data.insights.agreements)].map(a=><li key={a}><Check size={16}/>Dezelfde keuze rond {a}</li>)}</ul>:<p>Wanneer jullie allebei antwoorden, verschijnen hier de eerste overeenkomsten.</p>}</div><div className="paper"><span className="eyebrow">DAAR ZIT EEN GESPREK</span><h2>Eigenzinnige verschillen</h2>{data?.insights.differences.length?<ul>{data.insights.differences.map(a=><li key={a}>{a}</li>)}</ul>:<p>Nog geen zichtbare verschillen. Eerst kiezen jullie allebei, daarna kijken we samen.</p>}</div><div className="paper soft"><Sparkles size={26}/><h2>De volgende ontdekking</h2><p>We wisselen onderwerpen af en kiezen vragen over wat nog open ligt. Een patroon tussen duur en comfort vraagt meer bewijs dan één antwoord.</p></div></div><Link href="/test" className="quiet preview-entry"><Sparkles size={17}/> Testflow zonder opslag</Link>{setTotals()}<button className="quiet" onClick={()=>go('history')}><History size={18}/> Bekijk de eerdere keuzes</button></>}
    {screen==='report'&&<><div className="page-heading"><span className="eyebrow">POST UIT JULLIE TOEKOMST</span><h1>Een reis die op jullie lijkt.</h1><p>{data?`Week van ${data.report.week} · jullie wekelijkse moment`:'Iedere week een nieuwe bladzijde, op basis van jullie keuzes.'}</p></div><section className="report paper"><div className="report-header"><span className="stamp">REISPOST · {data?.report.week??'VOORPRET'}</span><Compass size={34}/></div><Travelers members={data?.members.length===2?data.members:undefined} size={54}/><h2>Beste toekomstige reisgenoten,</h2><p className="report-lead">{report?.dna??'Jullie reisverhaal begint met een kleine keuze. Maak samen een boekje aan en ontdek waar jullie dromen elkaar raken.'}</p><div className="report-match"><Heart size={22}/><b>{report?.match===null||!report?'Nog even ontdekken':`${report.match}% dezelfde keuzes`}</b><span>Een speelse interne score · {report?.complete??0} gezamenlijke dilemma’s</span></div><h3>Waar jullie elkaar vinden</h3><p>{report?.agreements.length?[...new Set(report.agreements)].join(' · '):'De eerste gezamenlijke antwoorden komen hier terug.'}</p><h3>Waar het gaat kriebelen</h3><p>{report?.differences.length?report.differences.join(' · '):'Nog geen onderbouwde verschillen zichtbaar.'}</p><h3>Een nieuwe ontdekking</h3><p>{report?.discovery??'Voor een patroon hebben we meer dan één keuze nodig.'}</p><div className="fantasy"><span className="eyebrow">EEN FANTASIEREIS · NOG NIETS TE BOEKEN</span><Landscape/><h2>Stel je eens voor…</h2><p>{report?.fantasy??'Een trein die de bergen in rijdt. Een huisje waar de koffie al ruikt. Tijd om nergens naartoe te hoeven. Dit is een voorbeeld; jullie antwoorden maken het persoonlijk.'}</p></div><div className="feedback"><h3>Klopt dit een beetje?</h3><div>{[['love','😍 Heel erg'],['partly','🙂 Deels'],['no','🤨 Niet echt']].map(([rating,label])=><button key={rating} disabled={busy} onClick={()=>data?void action({action:'feedback',reportId:data.report.id,rating}).then(ok=>{if(ok)setNotice(demo?'Alleen geprobeerd. Deze feedback wordt niet opgeslagen.':'Dank je. Je feedback staat bij dit rapport.');}):setAuth('register')}>{label}</button>)}</div><p>Het weekrapport is een momentopname. Nieuwe antwoorden tellen mee in het volgende rapport.</p></div></section></>}
    {screen==='pair'&&<><div className="page-heading"><span className="eyebrow">EEN AVONTUUR VOOR TWEE</span><h1>Met wie ga je dromen?</h1><p>Deel je uitnodiging met je reisgenoot. Ieder krijgt een eigen account.</p></div>{!data?<Empty text="Begin met je eigen naam en avatar." onClick={()=>setAuth('register')}/>:partner?<div className="paper pair-complete"><Avatar id={data.user.avatar} size={74}/><Heart/><Avatar id={Number(partner.avatar)} size={74}/><h2>{data.user.name} & {String(partner.name)}</h2><p>Jullie boekje is gekoppeld. Tijd voor de eerste keuze.</p><SketchButton onClick={()=>go('today')}>Naar vandaag <ArrowRight size={18}/></SketchButton></div>:<div className="paper pairing"><h2>Nodig je reisgenoot uit</h2><p>Je uitnodiging is 7 dagen geldig en werkt één keer.</p><code>{data.invite}</code><SketchButton onClick={()=>{const url=`${location.origin}/?screen=pair&invite=${data.invite}`;if(navigator.clipboard)void navigator.clipboard.writeText(url).then(()=>setNotice('Uitnodigingslink gekopieerd.'));else setNotice(url);}}><LinkIcon size={17}/> Kopieer uitnodiging</SketchButton><hr/><h2>Zelf een uitnodiging gekregen?</h2><label>Uitnodigingscode<input value={inviteInput} onChange={e=>setInviteInput(e.target.value)} placeholder="Plak de code of uitnodigingslink"/></label><button className="choice" disabled={busy||!inviteInput} onClick={()=>{const code=inviteInput.includes('invite=')?inviteInput.split('invite=')[1].split('&')[0]:inviteInput;void action({action:'join',code}).then(ok=>{if(ok)go('pair');});}}>Koppel ons boekje <ArrowRight size={18}/></button><p className="privacy-note">Koppel voordat je je eerste antwoord geeft.</p></div>}</>}
    {screen==='preferences'&&<><div className="page-heading"><span className="eyebrow">WAT WE AL WETEN · WAT NOG OPEN LIGT</span><h1>Onze reisuitgangspunten.</h1><p>Een interesse is geen harde grens. Pas dit samen aan; nieuwe sets nemen jullie afspraken mee. De zeildroom van Roebie staat apart van Oelies nog open dromen.</p></div>{data&&<PreferenceEditor preferences={data.preferences} busy={busy} onSave={async payload=>{const ok=await action(payload);if(ok&&!demo)setNotice('Uitgangspunt opgeslagen. Nieuwe sets gebruiken deze afspraak.');return ok;}}/>}<button className="quiet" onClick={()=>go('settings')}>Terug naar instellingen</button></>}
    {screen==='settings'&&<><div className="page-heading"><span className="eyebrow">MAAK HET JULLIE BOEKJE</span><h1>De kleine instellingen.</h1></div>{data&&<button className="small-card" onClick={()=>go('preferences')}><Compass size={24}/><div><h3>Onze reisuitgangspunten</h3><p>Grenzen, eigen wensen en wat nog open ligt</p></div><ArrowRight size={20}/></button>}<div className="settings-grid"><section className="paper"><h2>{data?'Dit ben jij':'Welkom, reisgenoot'}</h2>{data?<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void action({action:'profile',name:form.get('name'),avatar}).then(ok=>{if(ok)setNotice('Je profiel is bijgewerkt.');});}}><label>Je naam<input name="name" defaultValue={data.user.name} required maxLength={40}/></label><p>Kies je getekende gezicht</p><AvatarPicker selected={avatar} onSelect={setAvatar}/><SketchButton disabled={busy} type="submit">Bewaar mijn profiel</SketchButton></form>:<SketchButton onClick={()=>setAuth('register')}>Begin jullie boekje</SketchButton>}<button className="quiet" onClick={()=>go('pair')}><LinkIcon size={17}/> Reispartner koppelen</button><button className="quiet" onClick={()=>go('sets')}><Compass size={17}/> Alle sets</button><button className="quiet" onClick={()=>go('history')}><History size={17}/> Antwoordgeschiedenis</button>{data&&<button className="quiet" onClick={()=>void action({action:'logout'}).then(()=>go('today'))}><LogOut size={17}/> Uitloggen</button>}</section><section className="paper"><Bell size={27}/><h2>Een klein seintje</h2><p>Dagelijkse voorpret en een nieuw reisrapport. Alleen tussen 09:00 en 21:00, Nederlandse tijd. Het tijdstip mag iedere dag anders zijn.</p><SketchButton disabled={!data||busy} onClick={()=>void enablePush()}>Zet berichtjes aan</SketchButton>{data&&<button className="quiet" onClick={()=>void action({action:'unsubscribe'}).then(ok=>{if(ok)setNotice('Berichtjes staan uit.');})}>Berichtjes uitzetten</button>}<button className="quiet" onClick={()=>go('install')}><Download size={17}/> App op je beginscherm</button></section><section className="paper privacy"><h2>Alleen jullie twee</h2><Link href="/fotocredits" className="quiet">Bekijk alle sfeerbeelden en fotocredits ↗</Link><p>{demo?'Tijdens proefreizen blijven alle keuzes alleen in deze tab. Er gaan geen antwoorden naar de server. Opnieuw laden begint weer leeg.':'Jullie antwoorden staan in een database, niet alleen op deze telefoon. Andere reisduo’s kunnen er niet bij. Je partner ziet je antwoord pas na een eigen keuze.'}</p><p>{data?'Op dit moment gebruik je de app via deze server.':'Na het aanmaken van een account worden keuzes echt opgeslagen.'} Online hosting maakt hetzelfde boekje vanaf iedere plek bereikbaar.</p></section></div></>}
    {screen==='install'&&<><div className="page-heading"><span className="eyebrow">ALTIJD EEN BEETJE VOORPRET BIJ JE</span><h1>Een plekje op je beginscherm.</h1><p>Deze app werkt op je telefoon én laptop.</p></div><section className="paper install"><Download size={38}/><h2>Installeer Samen op reis</h2>{install?<SketchButton disabled={demo} onClick={()=>void install.prompt()}>Installeer de app</SketchButton>:<p>Zie je geen installatieknop? Gebruik het menu van je browser om de app te installeren.</p>}<h3>Op iPhone of iPad</h3><ol><li>Open de online app in Safari.</li><li>Tik op Delen (het vierkant met het pijltje).</li><li>Kies ‘Zet op beginscherm’ en dan ‘Voeg toe’.</li><li>Open de app via het nieuwe icoon. Zet daarna berichtjes aan.</li></ol><h3>Op Android of laptop</h3><p>Kies ‘App installeren’ of ‘Toevoegen aan startscherm’ in Chrome of Edge.</p><p className="privacy-note">Installatie en push werken via HTTPS of localhost. Via het lokale wifi-adres kun je de mobiele weergave proberen; volledige installatie volgt op de online versie.</p><button className="quiet" onClick={()=>go('settings')}>Naar berichtjes <ArrowRight size={18}/></button></section></>}
    {demo&&<PreviewToolbar state={preview} onSwitch={id=>{const nextState={...preview,active:id};setPreview(nextState);setNotice('');setSelected(null);if(['reveal','question','done'].includes(screen)){const next=previewDashboard(nextState).questions.find(q=>q.own===null&&!preview.saved.includes(q.id));go(next?'question':'done',next?.id);}}} onReset={()=>{setPreview(initialPreview());setNotice('');go('question',previewQuestions[0].id);}} onCap={()=>setPreview(state=>({...state,roebieCap:!state.roebieCap}))} onNotification={()=>go('notification')} onReport={()=>{setPreview(previewWeek);go('report');}}/>}
    {!loaded&&<p className="loading-status" role="status">Je boekje openen…</p>}
    </div></main><nav className="mobile-nav" aria-label="Mobiele navigatie">{nav.map(item=><button className={screen===item.id?'active':''} key={item.id} onClick={()=>go(item.id)}><item.icon size={21}/><span>{item.label}</span></button>)}</nav>
    {auth&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="auth-title" className="auth-modal paper"><button className="modal-close" aria-label="Sluiten" onClick={()=>setAuth(null)}><X/></button><Compass size={32}/><h2 id="auth-title">{auth==='register'?'Jullie avontuur begint klein.':'Daar ben je weer.'}</h2><p>{auth==='register'?'Eén boekje, twee reisgenoten. Begin met jezelf.':'Open je reisnotitieboek.'}</p><form onSubmit={e=>void submitAuth(e)}>{auth==='register'&&<><label>Hoe heet je?<input name="name" autoComplete="given-name" placeholder="Bijvoorbeeld Ruben" required maxLength={40}/></label><AvatarPicker selected={avatar} onSelect={setAvatar}/></>}<label>E-mailadres<input type="email" name="email" autoComplete="email" required/></label><label>Wachtwoord<input type="password" name="password" autoComplete={auth==='register'?'new-password':'current-password'} minLength={10} maxLength={128} required placeholder="Minimaal 10 tekens"/></label><SketchButton type="submit" disabled={busy}>{busy?'Even je boekje pakken…':auth==='register'?'Maak mijn boekje':'Open mijn boekje'} <ArrowRight size={18}/></SketchButton></form><button className="quiet" onClick={()=>setAuth(auth==='register'?'login':'register')}>{auth==='register'?'Al een boekje? Log in':'Nog geen boekje? Begin hier'}</button>{notice&&<p role="alert">{notice}</p>}</section></div>}
  </div>;
}
function Empty({text,onClick}:{text:string;onClick:()=>void}) {return <section className="paper empty"><Landscape kind="house"/><h2>{text}</h2><SketchButton onClick={onClick}>Naar de eerste keuze <ArrowRight size={17}/></SketchButton></section>;}
function AvatarPicker({selected,onSelect}:{selected:number;onSelect:(n:number)=>void}) {return <div className="avatar-picker" role="group" aria-label="Kies je avatar">{AVATARS.map(person=><button key={person.id} type="button" aria-label={`Kies ${person.name}`} aria-pressed={selected===person.id} onClick={()=>onSelect(person.id)}><Avatar id={person.id} size={46}/></button>)}</div>;}
