export const schema = `
CREATE TABLE IF NOT EXISTS app_migrations (version text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS avatars (id integer PRIMARY KEY, name text NOT NULL);
CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, email text NOT NULL UNIQUE, name text NOT NULL, password_hash text NOT NULL, avatar integer NOT NULL REFERENCES avatars(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS travel_pairs (id text PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memberships (user_id text PRIMARY KEY REFERENCES users(id), pair_id text NOT NULL REFERENCES travel_pairs(id), slot integer NOT NULL CHECK(slot IN (1,2)), UNIQUE(pair_id,slot));
CREATE TABLE IF NOT EXISTS invites (code text PRIMARY KEY, pair_id text NOT NULL REFERENCES travel_pairs(id), expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE IF NOT EXISTS questions (id text PRIMARY KEY, content jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS question_options (question_id text REFERENCES questions(id), choice integer CHECK(choice IN (0,1)), content jsonb NOT NULL, PRIMARY KEY(question_id,choice));
CREATE TABLE IF NOT EXISTS attributes (key text PRIMARY KEY, value_type text NOT NULL);
CREATE TABLE IF NOT EXISTS attribute_values (id text PRIMARY KEY, attribute_key text NOT NULL REFERENCES attributes(key), value jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS question_option_attributes (question_id text, choice integer, attribute_key text REFERENCES attributes(key), value_id text REFERENCES attribute_values(id), PRIMARY KEY(question_id,choice,attribute_key), FOREIGN KEY(question_id,choice) REFERENCES question_options(question_id,choice));
CREATE TABLE IF NOT EXISTS answers (user_id text REFERENCES users(id), pair_id text NOT NULL REFERENCES travel_pairs(id), question_id text REFERENCES questions(id), choice integer NOT NULL CHECK(choice IN (0,1)), snapshot jsonb NOT NULL, answered_at timestamptz NOT NULL DEFAULT now(), mode text NOT NULL CHECK(mode IN ('daily','later')), information_value real, confidence real, PRIMARY KEY(user_id,question_id));
CREATE TABLE IF NOT EXISTS saved_questions (user_id text REFERENCES users(id), pair_id text NOT NULL REFERENCES travel_pairs(id), question_id text REFERENCES questions(id), saved_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,question_id));
CREATE TABLE IF NOT EXISTS daily_assignments (pair_id text REFERENCES travel_pairs(id), day text, question_id text REFERENCES questions(id), position integer NOT NULL, PRIMARY KEY(pair_id,day,question_id), UNIQUE(pair_id,day,position));
CREATE TABLE IF NOT EXISTS weekly_reports (id text PRIMARY KEY, pair_id text NOT NULL REFERENCES travel_pairs(id), week text NOT NULL, content jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(pair_id,week));
CREATE TABLE IF NOT EXISTS report_feedback (report_id text REFERENCES weekly_reports(id), user_id text REFERENCES users(id), rating text NOT NULL CHECK(rating IN ('love','partly','no')), PRIMARY KEY(report_id,user_id));
CREATE TABLE IF NOT EXISTS preference_estimates (pair_id text REFERENCES travel_pairs(id), user_id text REFERENCES users(id), attribute_key text REFERENCES attributes(key), estimate real NOT NULL, observations integer NOT NULL, PRIMARY KEY(pair_id,user_id,attribute_key));
CREATE TABLE IF NOT EXISTS compatibility_insights (pair_id text PRIMARY KEY REFERENCES travel_pairs(id), content jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), subscription jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notification_deliveries (user_id text REFERENCES users(id), day text, kind text, sent_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,day,kind));
CREATE TABLE IF NOT EXISTS auth_attempts (key text PRIMARY KEY, attempts integer NOT NULL, window_start timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS preference_subjects (id text PRIMARY KEY, pair_id text NOT NULL REFERENCES travel_pairs(id), kind text NOT NULL CHECK(kind IN ('couple','person')), person_key text, user_id text REFERENCES users(id), UNIQUE(pair_id,person_key));
CREATE TABLE IF NOT EXISTS travel_preferences (id text PRIMARY KEY, subject_id text NOT NULL REFERENCES preference_subjects(id), attribute_key text NOT NULL, kind text NOT NULL CHECK(kind IN ('hard_constraint','soft_constraint','strong_preference','weak_preference','interest','personal_wish','open_question')), value jsonb, confidence real NOT NULL CHECK(confidence BETWEEN 0 AND 1), source text NOT NULL CHECK(source IN ('explicitly_stated','inferred')), notes text NOT NULL, boundary jsonb, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS preference_evidence (preference_id text REFERENCES travel_preferences(id), user_id text, question_id text, PRIMARY KEY(preference_id,user_id,question_id), FOREIGN KEY(user_id,question_id) REFERENCES answers(user_id,question_id));
CREATE TABLE IF NOT EXISTS question_sets (id text PRIMARY KEY, pair_id text NOT NULL REFERENCES travel_pairs(id), day text NOT NULL, ordinal integer NOT NULL CHECK(ordinal>0), question_ids jsonb NOT NULL, UNIQUE(pair_id,day,ordinal));
CREATE TABLE IF NOT EXISTS set_progress (user_id text REFERENCES users(id), day text NOT NULL, ordinal integer NOT NULL CHECK(ordinal>0), PRIMARY KEY(user_id,day));
INSERT INTO question_sets(id,pair_id,day,ordinal,question_ids) SELECT pair_id||':'||day||':1',pair_id,day,1,jsonb_agg(question_id ORDER BY position) FROM daily_assignments GROUP BY pair_id,day ON CONFLICT DO NOTHING;
`;
