import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
await page.goto('http://localhost:3100');await page.getByRole('heading',{name:'Langer weg of bijzonder blijven?'}).waitFor();await page.screenshot({path:'test-results/desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow');
await page.getByRole('button',{name:'Begin samen'}).click();await page.getByLabel('Hoe heet je?').fill('Reisgenoot');const email=`browser-${Date.now()}@example.com`;await page.getByLabel('E-mailadres').fill(email);await page.getByLabel('Wachtwoord',{exact:true}).fill('browser-test-123');await page.getByRole('button',{name:'Maak mijn boekje'}).click();await page.getByRole('heading',{name:'Met wie ga je dromen?'}).waitFor();await page.screenshot({path:'test-results/onboarding.png',fullPage:true});
await page.getByRole('button',{name:'Vandaag',exact:true}).last().click();await page.getByRole('button',{name:'Ik kies A'}).click();await page.getByRole('heading',{name:'Jouw keuze staat in het boekje.'}).waitFor();await page.screenshot({path:'test-results/reveal.png',fullPage:true});
await page.reload();await page.getByRole('heading',{name:'Jouw keuze staat in het boekje.'}).waitFor();assert.equal(errors.length,0,errors.join('\n'));
console.log('PASS: desktop, 390px mobile, onboarding, real answer, reveal, persisted answer after reload; no browser runtime errors. Screenshots in test-results/.');await browser.close();
