import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  await context.addCookies([{name:'travel-session',value:'preview-cookie-must-not-be-used',url:'http://localhost:3100'}]);
  const page=await context.newPage();page.setDefaultTimeout(10000);
  const apiRequests=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/**',route=>{apiRequests.push(route.request().url());return route.abort();});
  await mkdir('test-results',{recursive:true});await page.goto('http://localhost:3100/test');
  await page.getByRole('heading',{name:'Hoe lang mag ons nieuwe leven duren?'}).waitFor();
  await page.waitForFunction(()=>Boolean(document.querySelector('.option .choice')?.onclick));
  await page.locator('.option .travel-sketch').first().waitFor();
  assert.equal(await page.locator('.option img').count(),0);
  assert.notEqual(await page.locator('.travel-sketch').first().getAttribute('data-sketch'),await page.locator('.travel-sketch').last().getAttribute('data-sketch'));
  await page.screenshot({path:'test-results/test-desktop.png',fullPage:true});
  await page.locator('.option').first().click({position:{x:100,y:100}});
  await page.getByRole('heading',{name:'Is 35 graden nog vakantie?'}).waitFor();
  await page.getByRole('button',{name:'Speel als Roebie'}).click();
  await page.getByRole('heading',{name:'Hoe lang mag ons nieuwe leven duren?'}).waitFor();
  await page.getByRole('button',{name:/^Ik kies B:/}).click();
  await page.getByRole('heading',{name:'Is 35 graden nog vakantie?'}).waitFor();
  await page.getByRole('button',{name:'Instellingen',exact:true}).click();
  await page.getByRole('button',{name:'Antwoordgeschiedenis'}).click();
  await page.locator('.list-item').first().click();
  await page.getByRole('heading',{name:'Twee kanten. Eén avontuur.'}).waitFor();
  await page.screenshot({path:'test-results/test-reveal.png',fullPage:true});
  await page.getByRole('button',{name:'Speel als Oelie'}).click();
  for(let i=0;i<3;i++)await page.getByRole('button',{name:/^Ik kies A:/}).click();
  await page.getByRole('heading',{name:'Een setje dichterbij.'}).waitFor();
  assert.deepEqual(await page.locator('.set-totals small').allTextContents(),['1 set beantwoord','0 sets beantwoord']);
  await page.getByRole('button',{name:'Bekijk alle sets',exact:true}).click();
  await page.getByRole('heading',{name:'Alle sets in ons boekje.'}).waitFor();
  assert.equal(await page.locator('.archive-question').count(),4);
  await page.locator('.archive-question').first().click();
  await page.getByRole('heading',{name:'Twee kanten. Eén avontuur.'}).waitFor();
  await page.getByRole('button',{name:'Set afgerond',exact:true}).click();
  await page.getByRole('button',{name:'Nog een set',exact:true}).click();
  const secondSetQuestion=await page.locator('.daily-heading h1').innerText();
  await page.getByRole('button',{name:'Speel als Roebie'}).click();
  await page.getByRole('heading',{name:'Is 35 graden nog vakantie?'}).waitFor();
  for(let i=0;i<3;i++)await page.getByRole('button',{name:/^Ik kies A:/}).click();
  assert.deepEqual(await page.locator('.set-totals small').allTextContents(),['1 set beantwoord','1 set beantwoord']);
  await page.getByRole('button',{name:'Nog een set',exact:true}).click();
  assert.equal(await page.locator('.daily-heading h1').innerText(),secondSetQuestion);
  await page.getByRole('button',{name:'Bewaar voor later',exact:true}).click();
  await page.getByRole('button',{name:/^Op de bank/}).first().click();
  await page.locator('.list-item').first().click();
  await page.getByRole('button',{name:/^Ik kies A:/}).click();
  await page.getByRole('button',{name:'Instellingen',exact:true}).click();
  await page.getByRole('button',{name:/Onze reisuitgangspunten/}).click();
  await page.getByRole('heading',{name:'Onze reisuitgangspunten.'}).waitFor();
  await page.locator('.preference-list details').first().locator('summary').click();
  await page.getByLabel('Toelichting en uitzonderingen').first().fill('Testafspraak die bij reset verdwijnt');
  await page.getByRole('button',{name:'Bewaar dit uitgangspunt'}).first().click();
  await page.getByText('Uitgangspunt geprobeerd. Alleen in deze testronde.').waitFor();
  await page.getByText('Testopties',{exact:true}).click();
  await page.getByRole('button',{name:'Pet af',exact:true}).click();
  assert.ok(await page.getByRole('img',{name:'Roebie · kaal',exact:true}).count()>0);
  await page.getByRole('button',{name:'Test berichtje'}).click();
  await page.getByRole('button',{name:/Vier kleine keuzes/}).click();
  await page.getByRole('button',{name:/^Ik kies A:/}).waitFor();
  await page.getByRole('button',{name:'Voorbeeldweek'}).click();
  await page.getByRole('heading',{name:'Beste toekomstige reisgenoten,'}).waitFor();
  await page.getByRole('button',{name:/Heel erg/}).click();
  await page.getByText('Alleen geprobeerd. Deze feedback wordt niet opgeslagen.').waitFor();
  await page.getByRole('button',{name:'Bespreken',exact:true}).click();
  await page.getByLabel('Krabbels voor deze testronde').fill('De foto’s zijn fijn, nu de vraag bespreken.');
  await page.reload();await page.getByText('Nog even ontdekken',{exact:true}).waitFor();
  await page.getByText('Testopties',{exact:true}).click();await page.getByRole('button',{name:'Opnieuw',exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  const heading=await page.locator('.daily-heading h1').boundingBox();assert.ok(heading.y<50);
  const secondChoice=await page.getByRole('button',{name:/^Ik kies B:/}).boundingBox();
  const mobileNav=await page.locator('.mobile-nav').boundingBox();
  assert.ok(secondChoice.y+secondChoice.height<mobileNav.y,'both choices fit above the mobile navigation');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'test-results/test-mobile.png',fullPage:true});
  await page.getByRole('button',{name:/^Ik kies A:/}).focus();await page.keyboard.press('Space');
  await page.getByRole('heading',{name:'Is 35 graden nog vakantie?'}).waitFor();
  for(let i=0;i<3;i++)await page.getByRole('button',{name:/^Ik kies A:/}).click();
  await page.getByRole('heading',{name:'Een setje dichterbij.'}).waitFor();
  assert.deepEqual(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length})),{local:0,session:0});
  assert.equal(await page.evaluate(async()=>(await navigator.serviceWorker.getRegistrations()).length),0);
  assert.deepEqual(apiRequests,[]);assert.deepEqual(errors,[]);
  console.log('PASS: whole-card sketch click and keyboard, immediate questions, two-person reveal/history, shared sets and independent totals/cursors, saved questions, editable context, cap, notification, report/feedback/scratchpad, reset, desktop/mobile; no API/storage/SW writes.');
} finally {await browser.close();}
