import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  // Even an existing login cookie must not turn the preview into a live data flow.
  await context.addCookies([{ name: 'travel-session', value: 'preview-cookie-must-not-be-used', url: 'http://localhost:3100' }]);
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  const apiRequests = []; const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/api/**', route => { apiRequests.push(route.request().url()); return route.abort(); });
  await mkdir('test-results', { recursive: true });
  await page.goto('http://localhost:3100/test');
  await page.getByRole('heading', { name: 'Langer weg of bijzonder blijven?' }).waitFor();
  await page.screenshot({ path: 'test-results/test-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Ik kies A' }).click();
  await page.getByRole('heading', { name: 'Jouw keuze staat in het boekje.' }).waitFor();
  await page.getByRole('button', { name: 'Speel als Roebie' }).click();
  await page.getByRole('button', { name: 'Ik kies B' }).click();
  await page.getByRole('heading', { name: 'Twee kanten. Eén avontuur.' }).waitFor();
  await page.getByRole('button', { name: 'Speel als Oelie' }).click();
  await page.getByRole('heading', { name: 'Twee kanten. Eén avontuur.' }).waitFor();
  await page.screenshot({ path: 'test-results/test-reveal.png', fullPage: true });
  console.log('Two-person reveal passed');
  await page.getByRole('button', { name: 'Nog een kleine keuze' }).click();
  await page.getByRole('button', { name: 'Bewaar voor later', exact: true }).click();
  await page.getByRole('button', { name: /^Op de bank/ }).first().click();
  await page.locator('.list-item').first().click();
  await page.getByRole('button', { name: 'Ik kies A' }).click();
  await page.getByRole('button', { name: 'Speel als Roebie' }).click();
  await page.getByRole('button', { name: 'Ik kies A' }).click();
  await page.getByRole('heading', { name: 'Dezelfde kant op.' }).waitFor();
  console.log('Test options stage');
  await page.getByText('Testopties', { exact: true }).click();
  await page.getByRole('button', { name: 'Pet af', exact: true }).click();
  assert.ok(await page.getByRole('img', { name: 'Roebie · kaal', exact: true }).count() > 0);
  await page.getByRole('button', { name: 'Test berichtje' }).click();
  await page.getByRole('heading', { name: 'Stel: dit komt binnen.' }).waitFor();
  await page.getByRole('button', { name: /Vier kleine keuzes/ }).click();
  await page.getByRole('button', { name: 'Ik kies A' }).waitFor();
  console.log('Notification entry passed');
  await page.getByRole('button', { name: 'Voorbeeldweek' }).click();
  await page.getByRole('heading', { name: 'Beste toekomstige reisgenoten,' }).waitFor();
  await page.getByRole('button', { name: /Heel erg/ }).click();
  await page.getByText('Alleen geprobeerd. Deze feedback wordt niet opgeslagen.').waitFor();
  await page.getByRole('button', { name: 'Bespreken', exact: true }).click();
  await page.getByLabel('Krabbels voor deze testronde').fill('Mag de reveal nog speelser?');
  console.log('Report and scratchpad passed');
  await page.reload();
  await page.getByRole('heading', { name: 'Beste toekomstige reisgenoten,' }).waitFor();
  await page.getByText('Nog even ontdekken', { exact: true }).waitFor();
  console.log('Test options stage');
  await page.getByText('Testopties', { exact: true }).click();
  await page.getByRole('button', { name: 'Opnieuw', exact: true }).click();
  await page.getByRole('button', { name: 'Ik kies A' }).waitFor();
  await page.getByText('Testopties', { exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  const heading = await page.getByRole('heading', { name: 'Langer weg of bijzonder blijven?' }).boundingBox();
  const firstChoice = await page.getByRole('button', { name: 'Ik kies A' }).boundingBox();
  assert.ok(heading.y < 50, 'daily question starts at the top');
  assert.ok(firstChoice.y + firstChoice.height < 844 - 72, 'first choice is visible without scrolling');
  assert.ok(await page.locator('.preview-toolbar').evaluate(el => el.getBoundingClientRect().top) > firstChoice.y, 'test controls follow the choices');
  await page.screenshot({ path: 'test-results/test-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile has no horizontal overflow');
  assert.deepEqual(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length })), { local: 0, session: 0 });
  assert.equal(await page.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).length), 0);
  for (let i = 0; i < 4; i++) {
    await page.getByRole('button', { name: 'Ik kies A' }).click();
    await page.getByRole('button', { name: i === 3 ? 'Klaar voor vandaag' : 'Nog een kleine keuze' }).click();
  }
  await page.getByRole('heading', { name: 'Dat was jullie kleine reisje.' }).waitFor();
  assert.deepEqual(apiRequests, [], 'preview must never call the live API');
  assert.deepEqual(errors, [], 'no browser runtime errors');
  console.log('PASS: preview has no API/storage/SW writes, even with a login cookie; two-person answers, hidden/revealed choices, shared stack, cap toggle, notification entry, report, feedback, scratchpad, reload/reset, mobile.');
} finally { await browser.close(); }
