import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base='http://localhost:3100';
function client(){let cookie='';return async(payload)=>{const response=await fetch(`${base}/api/app`,{method:payload?'POST':'GET',headers:{Cookie:cookie,...(payload?{Origin:base,'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined});const session=response.headers.get('set-cookie');if(session)cookie=session.split(';')[0];return {status:response.status,data:await response.json()};};}
const a=client(),b=client(),other=client();
const nonce=Date.now();
for(const [i,user] of [a,b,other].entries())assert.equal((await user({action:'register',name:`Sets ${i}`,email:`sets-${nonce}-${i}@example.com`,password:'set-test-only-123',avatar:i})).status,200);
const first=(await a()).data;assert.equal((await b({action:'join',code:first.invite})).status,200);
assert.equal((await a({action:'next-set',setId:first.set.id})).status,409);
const warmth=first.preferences.find(p=>p.attribute==='temperature');
const payload={action:'preference',preferenceId:warmth.key,kind:'hard_constraint',notes:'Test: 20–30 graden is een harde grens',confidence:1,value:'warm_and_dry',boundary:{unit:'°C',hard:[20,30]}};
assert.equal((await other(payload)).status,403);
assert.equal((await a({...payload,boundary:{unit:'°C',hard:[30,20]}})).status,400);
assert.equal((await a(payload)).status,200);
assert.equal((await a()).data.preferences.find(p=>p.key===warmth.key).kind,'hard_constraint');
for(const q of first.questions)assert.equal((await a({action:'answer',questionId:q.id,choice:0})).status,200);
let current=(await a()).data;assert.deepEqual(current.setTotals.map(p=>p.completed),[1,0]);
const advanced=await Promise.all([a({action:'next-set',setId:first.set.id}),a({action:'next-set',setId:first.set.id})]);
assert.ok(advanced.every(r=>r.status===200));current=(await a()).data;assert.equal(current.set.ordinal,2);
const second=current;assert.ok(second.questions.every(q=>!first.questions.some(p=>p.id===q.id)));
assert.equal((await b()).data.set.ordinal,1);
for(const q of first.questions)assert.equal((await b({action:'answer',questionId:q.id,choice:1})).status,200);
assert.deepEqual((await b()).data.setTotals.map(p=>p.completed),[1,1]);
assert.equal((await b({action:'next-set',setId:first.set.id})).status,200);
assert.deepEqual((await b()).data.questions.map(q=>q.id),second.questions.map(q=>q.id));
for(const q of second.questions)assert.equal((await a({action:'save',questionId:q.id})).status,200);
assert.equal((await a({action:'next-set',setId:second.set.id})).status,200);
assert.deepEqual((await a()).data.setTotals.map(p=>p.completed),[1,1]);
for(const q of second.questions)assert.equal((await a({action:'answer',questionId:q.id,choice:0,mode:'later'})).status,200);
assert.deepEqual((await a()).data.setTotals.map(p=>p.completed),[2,1]);
assert.equal((await other()).data.history.length,0);
await mkdir('test-results',{recursive:true});await writeFile('test-results/sets-persistence.json',JSON.stringify({email:`sets-${nonce}-0@example.com`,preferenceId:warmth.key}));
console.log('PASS: database context seed/edit, duo authorization, invalid boundaries, set readiness, concurrent idempotent advance, shared sets with independent cursors, all-time individual counts, save-and-complete-later.');
